language: cpp
os: linux
dist: focal # Use a recent Ubuntu distribution

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - jq # For the run-benchmarks.sh script

install:
  - git submodule update --init --recursive # Initialize and update all submodules

script:
  - mkdir build
  - cd build
  - cmake .. -DSUBMIT_TO_CDASH=ON -Dalg_BUILD_TESTS=ON # Configure with CDash submission enabled
  - make build_all_forks # Build all external dependencies and forks
  - make alg_project # Build the main project
  - make test-all # Run all tests and submit to CDash
