# This script is injected into the configuration of external projects (forks)
if(DEFINED CMAKE_PREFIX_PATH)
  include_directories(${CMAKE_PREFIX_PATH}/include)
  link_directories(${CMAKE_PREFIX_PATH}/lib)
else()
  error("Improperly called without a CMAKE_PREFIX_PATH")
endif()

find_package(benchmark REQUIRED)
find_package(GTest REQUIRED)
include(GoogleTest)
include_directories(${GTest_INCLUDE_DIRS})
enable_testing()
#include_directories(${BENCHMARK_INCLUDE_DIRS})
